In [1]:
import pandas as pd
loans_2007=pd.read_csv(r'C:\Users\Ordinary\Desktop\LoanStats3a.csv',skiprows=1)
half_count=len(loans_2007)/2
#print(loans_2007.head(3))
loans_2007=loans_2007.dropna(thresh=half_count,axis=1)
loans_2007=loans_2007.drop(['desc'],axis=1)
loans_2007.to_csv('loans_2007.csv',index=False)

D:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (0,47) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [2]:
import pandas as pd
loans_2007=pd.read_csv(r'C:\Users\Ordinary\Desktop\loans_2007.csv')
loans_2007.drop_duplicates()
print(loans_2007.iloc[0])
print(loans_2007.shape[1])

loan_amnt                            5000
funded_amnt                          5000
funded_amnt_inv                      4975
term                            36 months
int_rate                           10.65%
installment                        162.87
grade                                   B
sub_grade                              B2
emp_title                             NaN
emp_length                      10+ years
home_ownership                       RENT
annual_inc                          24000
verification_status              Verified
issue_d                          Dec-2011
loan_status                    Fully Paid
pymnt_plan                              n
purpose                       credit_card
title                            Computer
zip_code                            860xx
addr_state                             AZ
dti                                 27.65
delinq_2yrs                             0
earliest_cr_line                 Jan-1985
inq_last_6mths                          1
open_acc                                3
pub_rec                                 0
revol_bal                           13648
revol_util                          83.7%
total_acc                               9
initial_list_status                     f
out_prncp                               0
out_prncp_inv                           0
total_pymnt                       5863.16
total_pymnt_inv                   5833.84
total_rec_prncp                      5000
total_rec_int                      863.16
total_rec_late_fee                      0
recoveries                              0
collection_recovery_fee                 0
last_pymnt_d                     Jan-2015
last_pymnt_amnt                    171.62
last_credit_pull_d               Jan-2018
collections_12_mths_ex_med              0
policy_code                             1
application_type               Individual
acc_now_delinq                          0
chargeoff_within_12_mths                0
delinq_amnt                             0
pub_rec_bankruptcies                    0
tax_liens                               0
hardship_flag                           N
disbursement_method                  Cash
debt_settlement_flag                    N
Name: 0, dtype: object
53

In [18]:
print(loans_2007['loan_status'].value_counts())
print(loans_2007)

Fully Paid                                             34116
Charged Off                                             5670
Does not meet the credit policy. Status:Fully Paid      1988
Does not meet the credit policy. Status:Charged Off      761
Name: loan_status, dtype: int64
       loan_amnt  funded_amnt  funded_amnt_inv        term int_rate  \
0         5000.0       5000.0      4975.000000   36 months   10.65%
1         2500.0       2500.0      2500.000000   60 months   15.27%
2         2400.0       2400.0      2400.000000   36 months   15.96%
3        10000.0      10000.0     10000.000000   36 months   13.49%
4         3000.0       3000.0      3000.000000   60 months   12.69%
5         5000.0       5000.0      5000.000000   36 months    7.90%
6         7000.0       7000.0      7000.000000   60 months   15.96%
7         3000.0       3000.0      3000.000000   36 months   18.64%
8         5600.0       5600.0      5600.000000   60 months   21.28%
9         5375.0       5375.0      5350.000000   60 months   12.69%
10        6500.0       6500.0      6500.000000   60 months   14.65%
11       12000.0      12000.0     12000.000000   36 months   12.69%
12        9000.0       9000.0      9000.000000   36 months   13.49%
13        3000.0       3000.0      3000.000000   36 months    9.91%
14       10000.0      10000.0     10000.000000   36 months   10.65%
15        1000.0       1000.0      1000.000000   36 months   16.29%
16       10000.0      10000.0     10000.000000   36 months   15.27%
17        3600.0       3600.0      3600.000000   36 months    6.03%
18        6000.0       6000.0      6000.000000   36 months   11.71%
19        9200.0       9200.0      9200.000000   36 months    6.03%
20       20250.0      20250.0     19142.161077   60 months   15.27%
21       21000.0      21000.0     21000.000000   36 months   12.42%
22       10000.0      10000.0     10000.000000   36 months   11.71%
23       10000.0      10000.0     10000.000000   36 months   11.71%
24        6000.0       6000.0      6000.000000   36 months   11.71%
25       15000.0      15000.0     15000.000000   36 months    9.91%
26       15000.0      15000.0      8725.000000   36 months   14.27%
27        5000.0       5000.0      5000.000000   60 months   16.77%
28        4000.0       4000.0      4000.000000   36 months   11.71%
29        8500.0       8500.0      8500.000000   36 months   11.71%
...          ...          ...              ...         ...      ...
42508     6000.0       6000.0      1200.000000   36 months   13.12%
42509     5350.0       5350.0       625.000000   36 months   13.12%
42510     1900.0       1900.0       900.000000   36 months    9.64%
42511    10000.0      10000.0       350.000000   36 months   14.70%
42512     2000.0       2000.0      1275.000000   36 months    7.12%
42513     6000.0       6000.0       650.000000   36 months   10.59%
42514     4400.0       4400.0      1400.000000   36 months    9.64%
42515     1200.0       1200.0       500.000000   36 months    9.01%
42516     5000.0       5000.0       375.000000   36 months   11.22%
42517     1400.0       1400.0       475.000000   36 months   10.91%
42518     1000.0       1000.0       625.000000   36 months   14.07%
42519     5000.0       5000.0       300.000000   36 months    7.75%
42520     2500.0       2500.0       225.000000   36 months    7.43%
42521     3000.0       3000.0       250.000000   36 months    7.43%
42522     2600.0       2600.0       575.000000   36 months    8.38%
42523     1000.0       1000.0       625.000000   36 months    7.12%
42524     1275.0       1275.0         0.000000   36 months   12.49%
42525     6450.0       6450.0         0.000000   36 months   11.22%
42526    10500.0      10500.0       275.000000   36 months   11.22%
42527     3000.0       3000.0       125.000000   36 months    9.01%
42528     3000.0       3000.0         0.000000   36 months    9.33%
42529     2000.0       2000.0       225.000000   36 months    9.96%
42530     6500.0       6500.0         0.000000   36 months    9.64%
42531     3500.0       3500.0       225.000000   36 months   10.28%
42532     1000.0       1000.0         0.000000   36 months    9.64%
42533     2525.0       2525.0       225.000000   36 months    9.33%
42534     6500.0       6500.0         0.000000   36 months    8.38%
42535     5000.0       5000.0         0.000000   36 months    7.75%
42536        NaN          NaN              NaN         NaN      NaN
42537        NaN          NaN              NaN         NaN      NaN

       installment grade sub_grade  \
0           162.87     B        B2
1            59.83     C        C4
2            84.33     C        C5
3           339.31     C        C1
4            67.79     B        B5
5           156.46     A        A4
6           170.08     C        C5
7           109.43     E        E1
8           152.39     F        F2
9           121.45     B        B5
10          153.45     C        C3
11          402.54     B        B5
12          305.38     C        C1
13           96.68     B        B1
14          325.74     B        B2
15           35.31     D        D1
16          347.98     C        C4
17          109.57     A        A1
18          198.46     B        B3
19          280.01     A        A1
20          484.63     C        C4
21          701.73     B        B4
22          330.76     B        B3
23          330.76     B        B3
24          198.46     B        B3
25          483.38     B        B1
26          514.64     C        C2
27          123.65     D        D2
28          132.31     B        B3
29          281.15     B        B3
...            ...   ...       ...
42508       202.51     D        D5
42509       180.57     D        D5
42510        61.00     B        B4
42511       345.18     E        E5
42512        61.87     A        A1
42513       195.28     C        C2
42514       141.25     B        B4
42515        38.17     B        B2
42516       164.23     C        C4
42517        45.78     C        C3
42518        34.21     E        E3
42519       156.11     A        A3
42520        77.69     A        A2
42521        93.23     A        A2
42522        81.94     A        A5
42523        30.94     A        A1
42524        42.65     D        D3
42525       211.85     C        C4
42526       344.87     C        C4
42527        95.42     B        B2
42528        95.86     B        B3
42529        64.50     B        B5
42530       208.66     B        B4
42531       113.39     C        C1
42532        32.11     B        B4
42533        80.69     B        B3
42534       204.84     A        A5
42535       156.11     A        A3
42536          NaN   NaN       NaN
42537          NaN   NaN       NaN

                                           emp_title emp_length  \
0                                                NaN  10+ years
1                                              Ryder   < 1 year
2                                                NaN  10+ years
3                                AIR RESOURCES BOARD  10+ years
4                           University Medical Group     1 year
5                               Veolia Transportaton    3 years
6                          Southern Star Photography    8 years
7                                    MKC Accounting     9 years
8                                                NaN    4 years
9                                          Starbucks   < 1 year
10                             Southwest Rural metro    5 years
11                                              UCLA  10+ years
12               Va. Dept of Conservation/Recreation   < 1 year
13                                            Target    3 years
14                                             SFMTA    3 years
15                          Internal revenue Service   < 1 year
16                                 Chin's Restaurant    4 years
17                                          Duracell  10+ years
18                             Connection Inspection     1 year
19                      Network Interpreting Service    6 years
20                  Archdiocese of Galveston Houston    3 years
21                                    Osram Sylvania  10+ years
22                                         Value Air  10+ years
23                                  Wells Fargo Bank    5 years
24                                   bmg-educational     1 year
25                    Winfield Pathology Consultants    2 years
26                                       nyc transit    9 years
27                                         Frito Lay    2 years
28           Shands Hospital at the University of Fl  10+ years
29                                    Oakridge homes   < 1 year
...                                              ...        ...
42508                                      SUNY- ESF    2 years
42509          Clinton Shop Rite of Hunterdon County     1 year
42510                                      Scheduall     1 year
42511                                        GA-PCOM     1 year
42512                                    Tzigane Inc    7 years
42513                                Yale University   < 1 year
42514              Brick Township board of education    2 years
42515                             Classic Components   < 1 year
42516                         Compensation Solutions   < 1 year
42517  Stanford University Libraries, LOCKSS Project   < 1 year
42518                                         Macy's  10+ years
42519  Diamond Management and Technology Consultants  10+ years
42520                                      U.S. Bank    9 years
42521                                             NC     1 year
42522                           College Pro Painters    3 years
42523                                  Mana Products    6 years
42524                           Infinitely law group     1 year
42525                                 Apto Solutions    2 years
42526                             Town of Plainville    3 years
42527                                   Tanks Tavern   < 1 year
42528                                            NaN   < 1 year
42529                                            NaN   < 1 year
42530                                      Air Force   < 1 year
42531                                            NaN   < 1 year
42532                     Halping hands company inc.   < 1 year
42533                                            NaN   < 1 year
42534                                            NaN   < 1 year
42535                                      Homemaker  10+ years
42536                                            NaN        NaN
42537                                            NaN        NaN

              ...          policy_code  application_type acc_now_delinq  \
0             ...                  1.0        Individual            0.0
1             ...                  1.0        Individual            0.0
2             ...                  1.0        Individual            0.0
3             ...                  1.0        Individual            0.0
4             ...                  1.0        Individual            0.0
5             ...                  1.0        Individual            0.0
6             ...                  1.0        Individual            0.0
7             ...                  1.0        Individual            0.0
8             ...                  1.0        Individual            0.0
9             ...                  1.0        Individual            0.0
10            ...                  1.0        Individual            0.0
11            ...                  1.0        Individual            0.0
12            ...                  1.0        Individual            0.0
13            ...                  1.0        Individual            0.0
14            ...                  1.0        Individual            0.0
15            ...                  1.0        Individual            0.0
16            ...                  1.0        Individual            0.0
17            ...                  1.0        Individual            0.0
18            ...                  1.0        Individual            0.0
19            ...                  1.0        Individual            0.0
20            ...                  1.0        Individual            0.0
21            ...                  1.0        Individual            0.0
22            ...                  1.0        Individual            0.0
23            ...                  1.0        Individual            0.0
24            ...                  1.0        Individual            0.0
25            ...                  1.0        Individual            0.0
26            ...                  1.0        Individual            0.0
27            ...                  1.0        Individual            0.0
28            ...                  1.0        Individual            0.0
29            ...                  1.0        Individual            0.0
...           ...                  ...               ...            ...
42508         ...                  1.0        Individual            0.0
42509         ...                  1.0        Individual            0.0
42510         ...                  1.0        Individual            NaN
42511         ...                  1.0        Individual            0.0
42512         ...                  1.0        Individual            0.0
42513         ...                  1.0        Individual            0.0
42514         ...                  1.0        Individual            0.0
42515         ...                  1.0        Individual            NaN
42516         ...                  1.0        Individual            NaN
42517         ...                  1.0        Individual            NaN
42518         ...                  1.0        Individual            NaN
42519         ...                  1.0        Individual            NaN
42520         ...                  1.0        Individual            NaN
42521         ...                  1.0        Individual            NaN
42522         ...                  1.0        Individual            NaN
42523         ...                  1.0        Individual            NaN
42524         ...                  1.0        Individual            NaN
42525         ...                  1.0        Individual            NaN
42526         ...                  1.0        Individual            NaN
42527         ...                  1.0        Individual            NaN
42528         ...                  1.0        Individual            NaN
42529         ...                  1.0        Individual            NaN
42530         ...                  1.0        Individual            NaN
42531         ...                  1.0        Individual            NaN
42532         ...                  1.0        Individual            NaN
42533         ...                  1.0        Individual            NaN
42534         ...                  1.0        Individual            NaN
42535         ...                  1.0        Individual            NaN
42536         ...                  NaN               NaN            NaN
42537         ...                  NaN               NaN            NaN

      chargeoff_within_12_mths delinq_amnt pub_rec_bankruptcies tax_liens  \
0                          0.0         0.0                  0.0       0.0
1                          0.0         0.0                  0.0       0.0
2                          0.0         0.0                  0.0       0.0
3                          0.0         0.0                  0.0       0.0
4                          0.0         0.0                  0.0       0.0
5                          0.0         0.0                  0.0       0.0
6                          0.0         0.0                  0.0       0.0
7                          0.0         0.0                  0.0       0.0
8                          0.0         0.0                  0.0       0.0
9                          0.0         0.0                  0.0       0.0
10                         0.0         0.0                  0.0       0.0
11                         0.0         0.0                  0.0       0.0
12                         0.0         0.0                  0.0       0.0
13                         0.0         0.0                  0.0       0.0
14                         0.0         0.0                  0.0       0.0
15                         0.0         0.0                  0.0       0.0
16                         0.0         0.0                  0.0       0.0
17                         0.0         0.0                  0.0       0.0
18                         0.0         0.0                  0.0       0.0
19                         0.0         0.0                  0.0       0.0
20                         0.0         0.0                  0.0       0.0
21                         0.0         0.0                  0.0       0.0
22                         0.0         0.0                  0.0       0.0
23                         0.0         0.0                  0.0       0.0
24                         0.0         0.0                  0.0       0.0
25                         0.0         0.0                  0.0       0.0
26                         0.0         0.0                  0.0       0.0
27                         0.0         0.0                  0.0       0.0
28                         0.0         0.0                  0.0       0.0
29                         0.0         0.0                  0.0       0.0
...                        ...         ...                  ...       ...
42508                      NaN         0.0                  NaN       NaN
42509                      NaN         0.0                  NaN       NaN
42510                      NaN         NaN                  NaN       NaN
42511                      NaN         0.0                  NaN       NaN
42512                      NaN         0.0                  NaN       NaN
42513                      NaN         0.0                  NaN       NaN
42514                      NaN         0.0                  NaN       NaN
42515                      NaN         NaN                  NaN       NaN
42516                      NaN         NaN                  NaN       NaN
42517                      NaN         NaN                  NaN       NaN
42518                      NaN         NaN                  NaN       NaN
42519                      NaN         NaN                  NaN       NaN
42520                      NaN         NaN                  NaN       NaN
42521                      NaN         NaN                  NaN       NaN
42522                      NaN         NaN                  NaN       NaN
42523                      NaN         NaN                  NaN       NaN
42524                      NaN         NaN                  NaN       NaN
42525                      NaN         NaN                  NaN       NaN
42526                      NaN         NaN                  NaN       NaN
42527                      NaN         NaN                  NaN       NaN
42528                      NaN         NaN                  NaN       NaN
42529                      NaN         NaN                  NaN       NaN
42530                      NaN         NaN                  NaN       NaN
42531                      NaN         NaN                  NaN       NaN
42532                      NaN         NaN                  NaN       NaN
42533                      NaN         NaN                  NaN       NaN
42534                      NaN         NaN                  NaN       NaN
42535                      NaN         NaN                  NaN       NaN
42536                      NaN         NaN                  NaN       NaN
42537                      NaN         NaN                  NaN       NaN

      hardship_flag disbursement_method debt_settlement_flag
0                 N                Cash                    N
1                 N                Cash                    N
2                 N                Cash                    N

In [28]:
loans_2007=loans_2007[(loans_2007['loan_status']=='Fully Paid')| (loans_2007['loan_status']=='Charged')]

status_replace={
    'loan_status':{
        'Fully Paid' : 1,
        'Charged Off':0
    }
}
loans_2007=loans_2007.replace(status_replace)

In [31]:
orig_columns=loans_2007.columns
drop_columns=[]
for col in orig_columns:
    col_series=loans_2007[col].dropna().unique()
    if len(col_series)==1:
        drop_columns.append(col)
loans_2007=loans_2007.drop(drop_columns,axis=1)
print(drop_columns)

['loan_status', 'pymnt_plan', 'initial_list_status', 'out_prncp', 'out_prncp_inv', 'recoveries', 'collection_recovery_fee', 'collections_12_mths_ex_med', 'policy_code', 'application_type', 'acc_now_delinq', 'chargeoff_within_12_mths', 'delinq_amnt', 'tax_liens', 'hardship_flag', 'disbursement_method', 'debt_settlement_flag']

In [34]:
import pandas as pd
loans=loans_2007
null_counts=loans.isnull().sum()
print(null_counts)

loan_amnt                  0
funded_amnt                0
funded_amnt_inv            0
term                       0
int_rate                   0
installment                0
grade                      0
sub_grade                  0
emp_title               1980
emp_length                 0
home_ownership             0
annual_inc                 0
verification_status        0
issue_d                    0
purpose                    0
title                      8
zip_code                   0
addr_state                 0
dti                        0
delinq_2yrs                0
earliest_cr_line           0
inq_last_6mths             0
open_acc                   0
pub_rec                    0
revol_bal                  0
revol_util                34
total_acc                  0
total_pymnt                0
total_pymnt_inv            0
total_rec_prncp            0
total_rec_int              0
total_rec_late_fee         0
last_pymnt_d               0
last_pymnt_amnt            0
last_credit_pull_d         1
pub_rec_bankruptcies     579
dtype: int64

In [35]:
loans=loans.drop('pub_rec_bankruptcies',axis=1)
loans=loans.dropna(axis=0)
print(loans.dtypes.value_counts())

float64    18
object     17
dtype: int64

In [36]:
object_columns_df=loans.select_dtypes(include=['object'])
print(object_columns_df.iloc[0])

term                             36 months
int_rate                            13.49%
grade                                    C
sub_grade                               C1
emp_title              AIR RESOURCES BOARD
emp_length                       10+ years
home_ownership                        RENT
verification_status        Source Verified
issue_d                           Dec-2011
purpose                              other
title                             personel
zip_code                             917xx
addr_state                              CA
earliest_cr_line                  Feb-1996
revol_util                             21%
last_pymnt_d                      Jan-2015
last_credit_pull_d                Apr-2016
Name: 3, dtype: object

In [41]:
mapping_dict={
    'emp_length':{
        '10+ years':10,
        '9 years':9,
        '8 years':8,
        '7 years':7,
        '6 years':6,
        '5 years':5,
        '4 years':4,
        '3 years':3,
        '2 years':2,
        '1 year':1,
        '< 1 year': 0,
        'n/a':0
    }
}
#loans=loans.drop(['last_credit_pull_d','earliest_cr_line','addr_state','title'],axis=1)
loans['int_rate']=loans['int_rate'].str.rstrip('%').astype('float')
loans['revol_util']=loans['revol_util'].str.rstrip('%').astype('float')
loans=loans.replace(mapping_dict)

AttributeError: Can only use .str accessor with string values, which use np.object_ dtype in pandas